[package]
name = "nginx-tail"
version = "0.0.1"
edition = "2024"

[dependencies]
pico-args = { version = "0.5.0", features = ["eq-separator", "short-space-opt"] }
rustix = { version = "1.0.7", features = ["termios"] }
smol = "2.0.2"
