#!/bin/bash
set -eu
cd "$(dirname "$0")"
source helpers/helperhelper.sh


test_ci() {
	banner "ci"
	readarray -t tests <<<"$(sed -n '/^test_/{ s///; s/(.*//; p }' run_tests)"
	workflow=".github/workflows/ci.yml"
	exitcode=0
	for test in "${tests[@]}"
	do
		[[ "$test" == "all" ]] && continue
		if ! grep "run: ./run_tests $test" "$workflow" >/dev/null
		then
			>&2 echo "Missing CI: $workflow does not appear to test $test"
			>&2 echo "Please add this:"
			>&2 echo "  test-$test:"
			>&2 echo "    runs-on: ubuntu-latest"
			>&2 echo "    steps:"
			>&2 echo "      - uses: actions/checkout@v4"
			>&2 echo "      - run: ./run_tests $test"
			exitcode=1
		fi
	done

	[[ "$exitcode" == "0" ]] || exit "$exitcode"
}

test_clippy() {
    banner "cargo clippy"
    cargo clippy -- --deny warnings
    cargo clippy --release -- --deny warnings
}

test_fmt() {
	banner "cargo fmt"
	cargo fmt --all -- --check
}

test_shear() {
	banner "cargo shear"
	pre=$(git status Cargo.toml --porcelain)
	if [[ -n "$pre" ]]
	then
		echo "Can't test: Cargo.toml isn't committed."
		return
	fi
	if ! cargo shear --help >/dev/null 2>&1
	then
		die "Command not found: cargo shear. Please install it: cargo install cargo-shear"
	fi
	cargo shear --fix
	post=$(git status Cargo.toml --porcelain)
	if [[ -n "$post" ]]
	then
		die "Unused dependencies as reported by 'cargo shear --fix'. See 'git diff'"
	fi
}

test_shellcheck() {
	banner "ShellCheck"
	command -v shellcheck >/dev/null || die "Please install shellcheck first: sudo apt install shellcheck"

	# TODO: Check we've tested all Bash scripts
	shellcheck -x helpers/helperhelper.sh run_tests
}

test_markdown() {
	# This is really commonmark, not Markdown.
	banner "Markdown"

	[[ -d "./venv/" ]] || {
		echo "Setting up a venv..."
		python3 -m venv venv;
	}

	[[ -e "./venv/bin/pymarkdown" ]] || {
		# If we ever change the version we'll have to add version check to this method
		echo "Installing pymarkdownlnt..."
		./venv/bin/pip install pymarkdownlnt==0.9.30;
	}

	./venv/bin/pymarkdown scan ./*.md
}

test_release() {
	banner "Release with musl"
	./build_release
}

test_test() {
	banner "cargo test"
	cargo test
}

test_all() {
	test_shear

	echo ""
	test_clippy

	echo ""
	test_fmt

	echo ""
	test_shellcheck

	echo ""
	test_markdown

	echo ""
	test_test

	echo ""
	test_release

	echo ""
	test_ci
}

if [[ $# -eq 0 ]]
then
	test_all
else

	while [[ $# -gt 0 ]]
	do
		func="test_$1"
		if command -v "$func" >/dev/null
		then
			"$func"
		else
			die "Unknown test $1"
		fi
		shift
	done
fi

echo ""
echo "All testcases passed."
