name: ci

on:
  push:
    branches:
      - main
      - 'feat-*'

env:
  CARGO_TERM_COLOR: always
  TERM: ansi

jobs:

  test-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup --version
      - run: ./run_tests test

  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup --version
      - run: rustup target add x86_64-unknown-linux-musl
      - run: ./run_tests release

  test-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_tests fmt

  test-shear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-shear
      - run: ./run_tests shear

  test-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_tests shellcheck

  test-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_tests markdown

  test-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_tests ci

  test-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_tests clippy

  test-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-audit --locked
      - run: ./run_tests audit
